### ISSUE TITLE
[Integrate] As a user, I will be blocked from UI interactive in some specific cases

### ISSUE THREAD

**Issue by markgravity** [markgravity/flutter-survey#22]
## Why

User should be blocked from UI interactive in some specific cases, such as: pressing a button to call login API
 
## Acceptance Criteria

User can't interact when HUD progress show up

**Comment by sleepylee** [comment]
not lol sure if this is a thing for every API calls, then that would be a bad UX. I'm suspecting that you are planning for the Login API only right?

**Comment by markgravity** [comment]
> not lol sure if this is a thing for every API calls, then that would be a bad UX. I'm suspecting that you are planning for the Login API only right?

It's one of them, but I can't choose a general word to describe that I want to block UI in some situations lol

**Comment by sleepylee** [comment]
@markgravity you can add that detail: "only in some specific occasions like pressing a button to call login API..."

**Comment by markgravity** [comment]
> @markgravity you can add that detail to the description: "only in some specific occasions like pressing a button to call login API..."

Sound good, I will update it 👍
