### ISSUE TITLE
[UI] As a user, I can login with my email and password

### ISSUE THREAD

**Issue by markgravity** [markgravity/flutter-survey#9]
## Why

When the user wants to log in, they can use their email and password
 
## Acceptance Criteria
https://www.figma.com/file/GjRPOjDyZ6f4EDL3wKarRK/Challenge-Mobile-App?node-id=31%3A195

![Sign in](https://user-images.githubusercontent.com/17875522/114332993-7e72e200-9b71-11eb-8aef-ca9f0b035edc.png)

**Comment by sleepylee** [comment]
i think the title is misalign with #23, "can see" should be UI ticket and "can do sth" should be Integrate yeah?🤙

**Comment by markgravity** [comment]
> i think the title is misalign with #23, "can see" should be UI ticket and "can do sth" should be Integrate yeah?🤙

I followed the example in the [compass](https://nimblehq.co/compass/product/backlog-management/user-stories/) 😁 
Also, I checked on my Toyota Wallet, we use the same title for UI/Integrate task (except [..])

**Comment by sleepylee** [comment]
@markgravity the convention is correct, Mark. What I meant is the content: on UI ticket you should work on the UI implementation so the user can see it right? And on the Integrate ticket you can integrate the backend call with an action from the UI to let the user 'do sth' no?

**Comment by markgravity** [comment]
> @markgravity the convention is correct, Mark. What I meant is the content: on UI ticket you should work on the UI implementation so the user can see it right? And on the Integrate ticket you can integrate the backend call with an action from the UI to let the user 'do sth' no?

Oh got your point, let's update it

**Comment by markgravity** [comment]
> @markgravity the convention is correct, Mark. What I meant is the content: on UI ticket you should work on the UI implementation so the user can see it right? And on the Integrate ticket you can integrate the backend call with an action from the UI to let the user 'do sth' no?

<img width="1241" alt="Screen Shot 2021-04-20 at 09 40 08" src="https://user-images.githubusercontent.com/17875522/115329405-742d9500-a1bc-11eb-87d2-1bb858c99b3e.png">
<img width="1259" alt="Screen Shot 2021-04-20 at 09 40 00" src="https://user-images.githubusercontent.com/17875522/115329411-77288580-a1bc-11eb-8b67-6e60a33922d0.png">

Which way I should follow now? 😢

**Comment by sleepylee** [comment]
@markgravity I think you misinterpreted the compass...notice the phase `when xyz`... it means that there is a UI already, and we need to apply condition to show it only when a specific condition is applied, hence it's an Integrate ticket.

**Comment by markgravity** [comment]
Your point is correct, but I don't feel strongly sure about using different descriptions there. At least, we used the same description in my project.

So lets me raise up on slack for this topic. What do you think? 😁

**Comment by sleepylee** [comment]
@markgravity first thing first: I started the convention of [UI] [Integrate] [Backend] title 🙏  second: I'm not asking you to change the `description - Why`, I'm asking about the title. In the end my suggestion was:
`[UI] As a user, I can see the login screen`

**Comment by markgravity** [comment]
Oh my bad. But we're still on the same situation because there are different ways in the title between my current project (compass example also) and your suggestion.
So I'm not sure which way I should follow 😢

**Comment by sleepylee** [comment]
![image](https://user-images.githubusercontent.com/13435717/115338947-1013cc80-a1ce-11eb-9a80-3222ecc94629.png)

even when the wording is a bit diverse from my suggestion above, which still be ok. But I'd like to emphasize that when you're having a plan or creating a ticket for yourself here, in such `[UI]` ticket, on a **mobile project**, we must target to work on the UI implementation. In this case, if you don't want to change your description to emphasize that you should work only in the UI implementation, then hence, I suggested you change the title with a small wording change. 

The choice is yours, as a developer, you can do this writing as minimal as efficient we want, but please be precise.

**Comment by sleepylee** [comment]
btw, in a real project, we are not doing this style, like in the example anymore, it was a bit lazy to duplicate the same content on all the [UI] [Backend] [Integrate] ticket. In fact, we do this only when a rare occasion for example we don't know how many APIs or which API to start with a specific feature. So here is what we would do nowadays i.e, in Dee Money project:

[UI] As a user, I can see the login screen
[Backend] As a user, I can call the API to login
[Integrate] As a user, I can log in
[Integrate] As a user, I will see an error when login with an invalid credential
[UI] As a user, I can see the error message popup
